name: ci

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "pypy-3.10"]

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
            python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe
          python -m pip install uv
        shell: bash
      - name: "Build"
        run: |
          set -xe
          python -VV
          python -m uv build --wheel --sdist
          python -m uv pip install dist/pyte*.whl
        shell: bash
      - name: "Run tests"
        run: |
          set -xe
          # Change directory to avoid importing pyte from repo root.
          pushd tests
          python -m uv run pytest -vv
          popd
        shell: bash
      - name: "Run mypy"
        run: |
          set -xe
          python -m uv run mypy pyte
        shell: bash
